spring.application.name=springBoot-liquibase-app

# =========================
#   Server Configuration
# ==========================

# ==========================
# active profile
spring.profile.active=dev
# ==========================

# server port
server.port = 7080

# datasource (H2 - in-memory)

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console

# DB H2 URL - http://localhost:7080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Optional : allow remote access
spring.h2.console.settings.web-allow-others=true

# Liquibase master changelog

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

#JPA is not used: using JDBC, if you add JPA, disable ddl-auto in prod

#spring.jpa.hibernate.ddl-auto=none