# server port

server.port = 7085

# Disable auto DDL in Prod Env

spring.jpa.hibernate.ddl-auto=none

# liquibase contexts
spring.liquibase.contexts= common,prod

# ================================
# Database Configuration
# ================================